version: '3.8'

x-logging: &logging
 driver: "json-file"
 options:
   max-size: "100m"
   max-file: "1"

services:
 nginx:
   image: nginx:latest
   ports:
     - "127.0.0.1:${WEB_PORT:-80}:80"
   volumes:
     - ./nginx:/etc/nginx/conf.d:rw
     - ./www:/var/www:ro
   restart: unless-stopped
   networks:
    backend:
     aliases:
       - nginx
    frontend:
   logging: *logging
   deploy:
     resources:
       limits:
         cpus: "${DOCKER_nginx_CPUS:-1}"
         memory: "${DOCKER_nginx_MEMORY:-200MB}"

 php:
   build: .
   volumes:
     - ./www:/var/www:ro
   restart: unless-stopped
#   depends_on:
#     nginx:
#      condition: service_healthy
   networks:
    backend:
     aliases:
       - php
   logging: *logging
   healthcheck:
     test: ["CMD","curl http://nginx:80 | grep works"]
     interval: 5s
     timeout: 5s
     retries: 20
   deploy:
     resources:
       limits:
         cpus: "${DOCKER_php_CPUS:-1}"
         memory: "${DOCKER_php_MEMORY:-200MB}"
        
networks:
 frontend:
   driver: bridge
   driver_opts:
      com.docker.network.enable_ipv6: "false"
   ipam:
     driver: default
     config:
      - subnet: 10.111.21.0/28
 backend:
   internal: true
   driver: bridge
   driver_opts:
    com.docker.network.enable_ipv6: "false"
   ipam:
     driver: default
     config:
      - subnet: 10.111.22.0/28   
