version: '3.8'

x-logging: &logging
 driver: "json-file"
 options:
   max-size: "100m"
   max-file: "1"

services:
 web:
   build: .
   ports:
     - "127.0.0.1:${WEB_PORT}:8000"
   depends_on:
     redis:
      condition: service_healthy
   restart: unless-stopped
   networks:
     - net
   logging: *logging


 redis:
   image: "redis:alpine"
   volumes:
     - redis-data:/data
   restart: unless-stopped
   networks:
     - net
   logging: *logging
   healthcheck:
     test: ["CMD","redis-cli","ping"]
     interval: 5s
     timeout: 5s
     retries: 20
   deploy:
     resources:
       limits:
         cpus: "${DOCKER_WEB_CPUS}"
         memory: "${DOCKER_WEB_MEMORY}"
        
networks:
 net:


volumes:
 redis-data: